

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: varnish-for-assets
data:
  default.vcl: |-
    vcl 4.0;
    backend default {
        .host = "localhost";
        .port = "80";
    }
    sub vcl_backend_response {
        set beresp.do_esi = true;
    }

---

apiVersion: v1
kind: Service
metadata:
  name: assets
  labels:
    app: assets
    role: frontend
    scs: assets
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: web
  selector:
    app: assets
    role: frontend
    scs: assets

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: assets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assets
      role: frontend
      scs: assets
  template:
    metadata:
      labels:
        app: assets
        role: frontend
        scs: assets
    spec:
      containers:
      - name: varnish-esi
        image: million12/varnish
        env:
          - name: VCL_CONFIG
            value: /etc/varnish/default.vcl
          - name: VARNISHD_PARAMS
            value: -a 0.0.0.0:8080
        volumeMounts:
        - name: varnish-config-volume
          mountPath: /etc/varnish/
      - name: assets
        image: starfish0r/assets:latest
        ports:
        - containerPort: 80
          name: web
      volumes:
      - name: varnish-config-volume
        configMap:
          name: varnish-for-assets

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-assets
spec:
  rules:
  - host: 3.g.ch.innoq.io
    http:
      paths:
      - path: /
        backend:
          serviceName: assets
          servicePort: 80


