apiVersion: v1
kind: ConfigMap
metadata:
  name: einbuchen-config
data:
  MONGO_SERVER: "mongo"
  INTERFACE: "0.0.0.0"
  PORT: "80"

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: einbuchen-crest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: einbuchen-crest
      role: backend
      scs: einbuchen
  template:
    metadata:
      labels:
        app: einbuchen-crest
        role: backend
        scs: einbuchen
    spec:
      initContainers:
      - name: config-creator
        image: busybox
        envFrom:
        - configMapRef:
            name: einbuchen-config
        command: ['/bin/sh', '-c', 'echo {\"db\": {\"port\": 27017,\"host\": \"$MONGO_SERVER\"},\"server\": {\"port\": 3500,\"address\": \"0.0.0.0\"},\"flavor\": \"mongodb\",\"debug\": true} > /config/config.json']
        volumeMounts:
         - name: config-volume
           mountPath: /config
      containers:
      - name: crest
        image: containerbootcamp/crest
        ports:
        - containerPort: 3500
          protocol: TCP
        volumeMounts:
          - name: config-volume
            mountPath: /etc/config
      volumes:
        - name: config-volume
          emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: einbuchen-crest
spec:
  ports:
  - port: 3500
    name: web
  selector:
    app: einbuchen-crest
    role: backend
    scs: einbuchen


