---

# Mounts a secret in a volume
# Projection of secret keys to specific paths
# Uses secrets from environment variables

apiVersion: v1
kind: Pod
metadata:
  name: secretbusybox
spec:
  containers:
  - name: busybox
    image: busybox
    env:
    - name: SECRET_USERNAME
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: username
    - name: SECRET_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: password
    args:
    - /bin/sh
    - -c
    - export ; ls /etc/secrets/ ; sleep 600
    volumeMounts:
    - name: secrets
      mountPath: /etc/secrets
      readOnly: true
    - name: specific-secret
      mountPath: /etc/specificSecret
      readOnly: true
  volumes:
  - name: secrets
    secret:
      secretName: mysecret
  - name: specific-secret
    secret:
      secretName: mysecret
      items: 
      - key: username
        path: my-group/my-username
